### ISSUE TITLE
Error when no answer is returned

### ISSUE THREAD

**Issue by alnguyen** [alnguyen/stackbot#6]
Kills the bot.  Handling isn't working properly!

`lookup [javascript] how do i delete first word from a string`

``` javascript
/Users/alan.nguyen/Documents/alan/stackbot/lib/Slackbot_worker.js:353
    msg.channel = src.channel
                ^

TypeError: Cannot set property 'channel' of undefined
    at Object.bot.reply (/Users/alan.nguyen/Documents/alan/stackbot/lib/Slackbot_worker.js:353:17)
    at Request._callback (/Users/alan.nguyen/Documents/alan/stackbot/services/stack-overflow.js:43:15)
    at Request.self.callback (/Users/alan.nguyen/Documents/alan/stackbot/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/alan.nguyen/Documents/alan/stackbot/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Gunzip.<anonymous> (/Users/alan.nguyen/Documents/alan/stackbot/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
```

**Comment by alnguyen** [comment]
Addressed with https://github.com/alnguyen/stackbot/pull/8
